
name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # Define the Node.js versions to test against
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4 # Check out the repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4 # Set up Node.js environment
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: "Install dependencies" 
      run: npm i # Install dependencies
    - name: "Build command"
      run: npm run build # Build the Next.js application
  
  unit-tests:

    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [18.x, 20.x, 22.x] # Define the Node.js versions to test against
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4 # Check out the repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # Set up Node.js environment
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: "Install dependencies" 
        run: npm i # Install dependencies
      - name: "Running unit tests"
        run: npm run test # Run unit tests